# Generated by Django 5.0.6 on 2024-06-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redberry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
