# Generated by Django 5.0.6 on 2024-06-25 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redberry', '0002_alter_generalinfo_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redberry.educationinfo')),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redberry.experienceinfo')),
                ('general', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redberry.generalinfo')),
            ],
        ),
    ]
