# Generated by Django 5.0.6 on 2024-06-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redberry', '0003_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='general',
        ),
        migrations.AddField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(to='redberry.educationinfo'),
        ),
        migrations.AddField(
            model_name='resume',
            name='experience',
            field=models.ManyToManyField(to='redberry.experienceinfo'),
        ),
        migrations.AddField(
            model_name='resume',
            name='general',
            field=models.ManyToManyField(to='redberry.generalinfo'),
        ),
    ]
