# Generated by Django 5.0.6 on 2024-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redberry', '0004_remove_resume_education_remove_resume_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, to='redberry.educationinfo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.ManyToManyField(blank=True, null=True, to='redberry.experienceinfo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='general',
            field=models.ManyToManyField(blank=True, null=True, to='redberry.generalinfo'),
        ),
    ]
