# Generated by Django 5.0.6 on 2024-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redberry', '0005_alter_resume_education_alter_resume_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(to='redberry.educationinfo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experience',
            field=models.ManyToManyField(to='redberry.experienceinfo'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='general',
            field=models.ManyToManyField(to='redberry.generalinfo'),
        ),
    ]
