# Generated by Django 5.0.6 on 2024-06-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redberry', '0006_alter_generalinfo_photo_alter_resume_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='photo',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
