# Generated by Django 5.0.6 on 2024-07-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redberry', '0007_alter_generalinfo_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalinfo',
            name='photo',
        ),
        migrations.AddField(
            model_name='resume',
            name='photo',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
