# Generated by Django 5.0.6 on 2024-07-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redberry', '0008_remove_generalinfo_photo_resume_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
